common/models/OrderTypes.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "order_types".
 *
 * @property integer $id
 * @property string $name
 */
class OrderTypes extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order_types';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
        ];
    }
}

backend/controllers/OrdersController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Orders;
use common\models\OrdersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrdersController implements the CRUD actions for Orders model.
 */
class OrdersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Orders models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Orders model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Orders model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Orders();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Orders model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Orders model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Orders model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Orders the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Orders::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/OrdersController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Cities;
use common\models\Orders;
use common\models\OrdersSearch;
use common\models\Coordinates;
use common\models\Userprofile;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
Yii::$app->view->registerJsFile('/js/core.js', ['depends' => 'yii\web\JqueryAsset']);
/**
 * OrdersController implements the CRUD actions for Orders model.
 */
class OrdersController extends Controller
{
    /**
     * @inheritdoc
     */
	public function beforeAction($action)
	{            
	    if ($action->id == 'checkphone' && $action->id == 'getlocaddr') {
	        $this->enableCsrfValidation = false;
	    }
	
	    return parent::beforeAction($action);
	}
    public function behaviors()
    {
        return [
			/*'access' => [
				'class' => AccessControl::className(),
				'only' => ['index','create','view','track','update','delate'],
				'rules' => [
					[
						'actions' => ['index','create','view','track','update','delate'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],*/
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Orders models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrdersSearch();
        $searchModel->client_id = Yii::$app->user->id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$model = Orders::find()->where(['client_id' => Yii::$app->user->id])->all();

        return $this->render('index', [
            //'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'model' => $model,
        ]);
    }

    /**
     * Displays a single Orders model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
    	$model = $this->findModel($id);
    	if($model->consignment == '350000')
    		$model->consignment = '350000'.$model->id;
        return $this->render('view', [
            'model' => $model,
        ]);
    }
    
    public function actionTrack($id)
    {
    	if(strpos($id,'350000') !== FALSE)
    		$id = (int)substr($id,5,strlen($id));
    	$model = $this->findModel($id);
    	
        return $this->render('track', [
            'model' => $model,
        ]);
    }
    
    public function actionTrack_search($id)
    {
    	if(strpos($id,'35000') !== FALSE)
    		$id = (int)substr($id,5,strlen($id));
    	$model = OrdersSearch::findOne($id);
    	if(!$model)
    		return $this->redirect(['/']);
        return $this->render('track', [
            'model' => $model,
        ]);
    }
    
    public function actionGetlocaddr()
    {
		$address = Yii::$app->request->post('address');
		$address .= ' united arab emirates';
		$address = str_replace(" ","+",$address);
		$url = 'https://maps.googleapis.com/maps/api/geocode/json?address='.$address.'&language=en&key=AIzaSyCSDBUqBwp7recbKeONWV5akmaRDw1MXI0';
		
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt ($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt ($ch, CURLOPT_SSL_VERIFYPEER, 0);
		curl_setopt($ch, CURLOPT_URL, $url);
		
		echo curl_exec($ch);
		
		//$direction = json_decode(curl_exec($ch));
    }
    
    public function actionCalculator()
    {
    	$val = NULL;

    	if(Yii::$app->request->isPost)
    	{
    		$order = new Orders;
    		$order->width = Yii::$app->request->post("width");
    		$order->height = Yii::$app->request->post("height");
    		$order->weight = Yii::$app->request->post("weight");
    		$order->length = Yii::$app->request->post("length");
    		$order->calculateCost();
    		$val = $order->cost;
    	}
    	if($val)
	    	$val = 'Delivery cost is '.$val;
	    else
	    	$val = 'Set your data for calculate';
		
		return $this->render('calculator',['val' => $val]);
    }
    
    public function actionCheckphone()
    {
    	$userArr = [];
		if((Yii::$app->request->post('phone')))
		{
			$users = Userprofile::find()->where(['like', 'phone', Yii::$app->request->post('phone')])->limit(3)->all();
			
			if($users)
			{
				foreach ($users as $user)
				{
					$userInfo = [];			
					$userInfo['id'] = $user->id;
					$userInfo['first_name'] = $user->first_name ? $user->first_name : "";
					$userInfo['last_name'] = $user->last_name ? $user->last_name : "";
					$userInfo['phone'] = $user->phone ? $user->phone : "";
					$userInfo['address'] = $user->street ? $user->street . ',' : "";
					$userInfo['address'] .= $user->bulding ? $user->bulding . ',': "";
					$userInfo['address'] .= $user->city_id ? Cities::findOne($user->city_id)->name : "";
					$userArr[$user->id] = $userInfo;
				}
			}
		}
		//\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
		return json_encode($userArr);
    }

    /**
     * Creates a new Orders model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Orders();
			
		if(!Yii::$app->user->isGuest)
		{
			$model->first_name = Yii::$app->user->attr('first_name');
			$model->last_name = Yii::$app->user->attr('last_name');
			$model->phone = Yii::$app->user->attr('phone');
		}
				
        if ($model->load(Yii::$app->request->post()) && $model->validate()) { //var_dump($model);exit;
    		$model->save();
    		$model->generateTTN();
    		$model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    /**
     * Updates an existing Orders model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id); 
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
        		$model->save();
        		$model->generateTTN();
        		$model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model
            ]);
        }
    }
    
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    protected function findModel($id)
    {
        if (($model = Orders::findOne($id)) !== null) {
        		if($model->client_id){
					if($userprofile = Userprofile::find()->where(['user_id' => $model->client_id])->one())
					{
        				$model->first_name = $userprofile->first_name ? $userprofile->first_name : '';
        				$model->last_name = $userprofile->last_name ? $userprofile->last_name : '';
        			}
        		}
        		if($model->date)
        			$model->date = date('Y-m-d',$model->date);
        		if($model->recipient_id && (int)$model->recipient_id > 0){
					if($userprofile = Userprofile::find()->where(['user_id' => $model->recipient_id])->one())
					{
        				$model->first_name_to = $userprofile->first_name ? $userprofile->first_name : '';
        				$model->last_name_to = $userprofile->last_name ? $userprofile->last_name : '';
        			}
        		}
        		if($model->from_id)
        			$model->address_from = Coordinates::findOne($model->from_id)->address;
        		if($model->to_id)
        			$model->address_to = Coordinates::findOne($model->to_id)->address;
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/orders/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\OrderTypes;
use common\models\Cities;
use common\models\Coordinates;
use dosamigos\datepicker\DatePicker;


/* @var $this yii\web\View */
/* @var $model common\models\Orders */
/* @var $form yii\widgets\ActiveForm */
?>
		
<div class="orders-form">

    <?php $form = ActiveForm::begin(); ?>
    <?php $userId = isset(Yii::$app->user->id) ? Yii::$app->user->id : '1'; ?>
    <?= $form->field($model, 'client_id')->hiddenInput(['value' => $userId])->label(false) ?>
    <?= $form->field($model, 'address_type')->hiddenInput(['value' => 'add'])->label(false)?>
    <?= $form->field($model, 'from_lat')->hiddenInput()->label(false)?>
    <?= $form->field($model, 'from_lon')->hiddenInput()->label(false)?>
    <?= $form->field($model, 'to_lat')->hiddenInput()->label(false)?>
    <?= $form->field($model, 'to_lon')->hiddenInput()->label(false)?>
    <?= $form->field($model, 'total_km')->hiddenInput()->label(false)?>
    
    <div class="col-md-12">
    	<div class="col-md-6">
				<div class="col-md-12 name-inform">
					<div class="col-md-6">
						<?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>
					</div>
					<div class="col-md-6 with-left-padding">
						<?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>
					</div>						
				</div>	
				
				<div class="col-md-12">
					<div class="col-md-7">
						<?= $form->field($model, 'phone',['template' => '
							<div class="form-group field-orders-address_to add-my-place-block">
								{label}
								<div class="input-group">
									<div class="input-group-addon">
										<img src="/images/phone-icon.png" width="32" height="32" alt="phone-icon">
									</div>
									{input}			
								</div>		
								<div class="inform-block"></div>
								<div class="help-block"></div>
							</div>
							'])->textInput(['maxlength' => true]) ?>
					</div>
					
					<div class="col-md-5">
						<?= $form->field($model, 'date')->widget(
				    		DatePicker::className(), [				    		
				    		'template' => '<div class="input-group-addon"><img src="/images/calendar-icon.png" width="32" height="32" alt="phone-icon"></div>{input}',
							    'clientOptions' => [
							            'autoclose' => true,
							            'format' => 'dd-mm-yyyy'
				        		]]); ?>
					</div>
				</div>
				<div class="col-md-12">
					<div class="col-md-5 add-my-place-block">
						<?= $form->field($model, 'address_from')->textInput(['maxlength' => true]) ?>
					</div>
					
					<div class="col-md-2">
						<?= $form->field($model, 'from_app')->textInput(['maxlength' => true]) ?>
					</div>
					<div class="col-md-5 form-group find-btn-div">
						<label class="control-label button-location-order">&nbsp</label>
						<button type="button" class="find-me btn btn-success btn-block">Find My Location</button>
					</div>
				</div>
				<div id="map"></div>
				
    	</div>
    	
    	<div class="col-md-6">
				<div class="col-md-12 name-inform">
					<div class="col-md-6">
						<?= $form->field($model, 'first_name_to')->textInput(['maxlength' => true]) ?>
					</div>
					<div class="col-md-6 with-left-padding">
						<?= $form->field($model, 'last_name_to')->textInput(['maxlength' => true]) ?>
					</div>	
				</div>	
				
				<div class="col-md-12">
					<div class="col-md-12 form-group field-orders-phone_to required">
						<label class="control-label" for="orders-phone_to">Recipient phone</label>
						<div class="input-group">
							<div class="input-group-addon">
								<img src="/images/phone-icon.png" width="32" height="32" alt="phone-icon">
							</div>
							<input type="text" id="orders-phone_to" class="form-control" name="Orders[phone_to]" maxlength="255" aria-required="true">
						</div>						
						
						<div class="help-block checkPhone"></div>
					</div>
				</div>
				
				<div class="col-md-12">
					<div class="col-md-5 add-my-place-block">
						<?= $form->field($model, 'address_to')->textInput(['maxlength' => true]) ?>
					</div>
					
					<div class="col-md-2">
						<?= $form->field($model, 'to_app')->textInput(['maxlength' => true]) ?>
					</div>
					<div class="col-md-5 form-group find-btn-div">
						<label class="control-label button-location-order">&nbsp</label>
						<button type="button" class="check-me btn btn-success btn-block">Check Location</button>
					</div>
				</div>
				
    		<div id="mapto"></div>
    	</div>
    	
    </div>
    
    
		<div id = "other">
		
		</div>
		
		
		
		<!--div class="col-md-12">
	    <div class="col-md-12 use-my-place-block places-blocks-to-show"<?= $model->isNewRecord ? ' style="display:none;"' : ''; ?>>
	    	<?= $form->field($model, 'from_id')->dropdownList(
	    		Coordinates::find()->select(['name', 'id'])->where(['user_id' => (int)Yii::$app->user->id])->indexBy('id')->column(),
	    		['prompt'=>Yii::t('app','My places')]) ?>
			</div>
			<div class="col-md-12 use-my-place-block places-blocks-to-show"<?= $model->isNewRecord ? ' style="display:none;"' : ''; ?>>
	    	<?= $form->field($model, 'to_id')->dropdownList(
	    		Coordinates::find()->select(['name', 'id'])->where(['user_id' => (int)Yii::$app->user->id])->indexBy('id')->column(),
	    		['prompt'=>Yii::t('app','My places')]) ?>
			</div>
		</div-->
		
		
		<div class="col-md-10">
			<div class="col-md-4 form-group">
				<label class="control-label" style="width:100%">Weight</label>
			</div>
			<div class="col-md-3"><?= $form->field($model, 'weight')->textInput()->label(false) ?></div>
		</div>
		
		<div class="col-md-10">
			<div class="col-md-4 form-group">
				<label class="control-label button-location-order" style="width:100%">&nbsp</label>
				<label class="control-label" style="width:100%">Dimension of departure</label>
			</div>
			<div class="col-md-2"><?= $form->field($model, 'height')->textInput() ?></div>
			<div class="col-md-2"><?= $form->field($model, 'width')->textInput() ?></div>
			<div class="col-md-2"><?= $form->field($model, 'length')->textInput() ?></div>
			<div class="col-md-2">
				<label class="control-label button-location-order" style="width:100%">&nbsp</label>
				<span class="pull-left">cm</span>
			</div>
		</div>
		<div class="col-md-9">
			<hr>
		</div>
		<div class="col-md-10">
			<div class="col-md-4 form-group">
				<label class="control-label button-location-order" style="width:100%">Number of seats</label>
			</div>
			<div class="col-md-3"><?= $form->field($model, 'seats')->textInput()->label(false) ?></div>
		</div>
		<div class="col-md-10">
			<div class="col-md-4 form-group">
				<label class="control-label button-location-order" style="width:100%">Announcement the cost</label>
			</div>
			<div class="col-md-3"><?= $form->field($model, 'ancost')->textInput()->label(false) ?></div>
		</div>
		<div class="col-md-9">
			<hr>
		</div>
		
		<div class="col-md-10">
			<div class="col-md-4 form-group">
				<label class="control-label button-location-order" style="width:100%">Type of return shipping</label>
			</div>
			<div class="col-md-3"><?= $form->field($model, 'type_id')->dropdownList([1=>'Sender','Recipient'])->label(false) ?></div>
		</div>
		
		<div class="col-md-10">
			<div class="col-md-4 form-group">
				<label class="control-label button-location-order" style="width:100%">Amount</label>
			</div>
			<div class="col-md-3"><?= $form->field($model, 'price')->textInput()->label(false) ?></div>			
		</div>

    <div class="form-group pull-right submit-delivery">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-danger']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script type="text/javascript">
var schools = [];
</script>

frontend/views/orders/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\OrdersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="orders-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'client_id') ?>

    <?= $form->field($model, 'vendor_id') ?>

    <?= $form->field($model, 'from_id') ?>

    <?= $form->field($model, 'to_id') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'city_id') ?>

    <?php // echo $form->field($model, 'adress') ?>

    <?php // echo $form->field($model, 'house') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <?php // echo $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'weight') ?>

    <?php // echo $form->field($model, 'length') ?>

    <?php // echo $form->field($model, 'width') ?>

    <?php // echo $form->field($model, 'height') ?>

    <?php // echo $form->field($model, 'cost') ?>

    <?php // echo $form->field($model, 'type_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/orders/calculator.php
<?php 
namespace frontend\views;
use Yii;
use yii\widgets\Pjax;
use yii\helpers\Html;


?>
<div class="container">

<?php Pjax::begin(['id' => 'calc-pj','timeout' => 50000 ]); ?>
	<?= Html::beginForm(['orders/calculator'], 'post', ['data-pjax' => '', 'class' => 'form-horizontal col-md-4 col-md-offset-4']); ?>
	<div class="form-group field-userprofile-first_name required">
		<label class="control-label" for="userprofile-first_name">Width</label>
		<?= Html::input('text', 'width', Yii::$app->request->post('width'), ['class' => 'form-control']) ?>		
		<p class="help-block help-block-error"></p>
	</div>
	
	<?= Html::beginForm(['orders/calculator'], 'post', ['data-pjax' => '', 'class' => 'form-inline']); ?>
	<div class="form-group field-userprofile-first_name required">
		<label class="control-label" for="userprofile-first_name">Height</label>
		<?= Html::input('text', 'height', Yii::$app->request->post('height'), ['class' => 'form-control']) ?>		
		<p class="help-block help-block-error"></p>
	</div>
	
	<?= Html::beginForm(['orders/calculator'], 'post', ['data-pjax' => '', 'class' => 'form-inline']); ?>
	<div class="form-group field-userprofile-first_name required">
		<label class="control-label" for="userprofile-first_name">Weight</label>
		<?= Html::input('text', 'weight', Yii::$app->request->post('weight'), ['class' => 'form-control']) ?>		
		<p class="help-block help-block-error"></p>
	</div>
	
	<?= Html::beginForm(['orders/calculator'], 'post', ['data-pjax' => '', 'class' => 'form-inline']); ?>
	<div class="form-group field-userprofile-first_name required">
		<label class="control-label" for="userprofile-first_name">Length</label>
		<?= Html::input('text', 'length', Yii::$app->request->post('length'), ['class' => 'form-control']) ?>		
		<p class="help-block help-block-error"></p>
	</div>
		
		<?= Html::submitButton('Calculate', ['class' => 'btn btn-info', 'name' => 'hash-button']) ?>
	<?= Html::endForm() ?>
	<p></p>
	<p class="col-md-12"><?=$val?></p>
<?php Pjax::end(); ?>
</div>

frontend/views/orders/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Orders */

$this->title = Yii::t('app', 'New Delivery');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Orders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="orders-create container">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model
    ]) ?>

</div>

frontend/views/orders/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Orders */

$this->title = '35000'.$model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Orders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="orders-view container">

    

    <p class="pull-right">
        <?= Html::a(Yii::t('app', 'Tracking'), Url::to(['orders/track', 'id' => '350000'.$model->id]), ['class' => 'btn btn-info']) ?>
        <?= Html::a(Yii::t('app', 'Edit'), ['update', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?php
    	if($model->status == "done") $classSpan="btn-default";
    	elseif($model->status == "in-progress") $classSpan="btn-info";
    	elseif($model->status == "pickup") $classSpan="btn-warning";    	
    	else $classSpan="btn-success";
    ?>
    <span class="pull-left btn <?=$classSpan?>" style="margin-top: 5px;"><?=$model->status?></span>
    <h3 class="pull-left">Delivery order <?=$model->consignment?></h3>
    
    <!--div class="col-md-12">
			<div class="col-md-12">
				<div class="col-md-6">
					<div class="col-md-12">
						<div class="col-md-5">Sender name</div>
						<div class="col-md-7"><?=$model->clientfio['first_name'].' '.$model->clientfio['last_name']?></div>
					</div>
					<div class="col-md-12">
						<div class="col-md-5">Sender address</div>
						<div class="col-md-7"><?=$model->address_from?></div>
					</div>
					<div class="col-md-12">
						<div class="col-md-5">Sender phone</div>
						<div class="col-md-7"><?=$model->phone?></div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="col-md-12">
						<div class="col-md-5">Recipient</div>
						<div class="col-md-7"><?=$model->vendorfio['first_name'].' '.$model->vendorfio['last_name']?></div>
					</div>
					<div class="col-md-12">
						<div class="col-md-5">Recipient address</div>
						<div class="col-md-7"><?=$model->address_to?></div>
					</div>
					<div class="col-md-12">
						<div class="col-md-5">Recipient phone</div>
						<div class="col-md-7"><?=$model->phone_to?></div>
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="col-md-2">Price</div>
				<div class="col-md-2">Weight</div>
				<div class="col-md-2">Length</div>
				<div class="col-md-2">Width</div>
				<div class="col-md-2">Height</div>
				<div class="col-md-2">Cost</div>
			</div>
			<div class="col-md-12">
				<div class="col-md-2"><?=$model->price?></div>
				<div class="col-md-2"><?=$model->weight?></div>
				<div class="col-md-2"><?=$model->length?></div>
				<div class="col-md-2"><?=$model->width?></div>
				<div class="col-md-2"><?=$model->height?></div>
				<div class="col-md-2"><?=$model->cost?></div>
			</div>
		</div-->
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            //'client_id',
			[
				'format' => 'raw',
				'attribute' => 'client_id',
				'value' => function($data){return $data->clientfio['first_name'].' '.$data->clientfio['last_name'] ;}
			],
			[
				'format' => 'raw',
				'attribute' => 'recipient_id',
				'value' => function($data){return $data->recipientfio['first_name'].' '.$data->recipientfio['last_name'] ;}
			],
			[
				'format' => 'raw',
				'attribute' => 'vendor_id',
				'value' => function($data){return $data->vendorfio['first_name'].' '.$data->vendorfio['last_name'] ;}
			],
			'consignment',
            //'from_id',
            //'to_id',
			'address_from',
			'address_to',
            'phone',
            'comment',
            'price',
            'weight',
            'length',
            'width',
            'height',
            'cost',
            [
            	'format' => 'raw',
            	'attribute' => 'type_id',
            	'value' => function($data){return $data->type_id == 1 ? 'Sender' : 'Recipient' ;}
            ]
        ],
    ]) ?>

</div>